### ISSUE TITLE
Fake LE Intermediate and Root X1

### ISSUE THREAD

**Issue by lagden** [will-in-wi/letsencrypt-webfaction#149]
Hi @will-in-wi 

I'm running the letsencrypt_webfaction 3.1.2
But now all my certificates are as: `Fake LE Intermediate and Root X1`

Some solutions that are in the forum are: `Check if you have a /etc/certbot/cli.conf file and if it sets something like" staging = true "or" test-cert = true ".`
https://community.letsencrypt.org/t/fake-le-intermediate-and-root-x1/55489

Follows my configuration file:
```toml
# Your Webfaction username and password
username = "myuser"
password = "*********"

# The email address which will be used to register with Let's Encrypt.
letsencrypt_account_email = "letsencrypt@lagden.in"

# endpoint = "https://acme-staging.api.letsencrypt.org/" # Staging
endpoint = "https://acme-v01.api.letsencrypt.org/" # Production
#api_url = "https://api.webfaction.com/"
#servername = "web531"

[[certificate]]
domains = [
  "brenohomaraimoveis.com.br",
  "www.brenohomaraimoveis.com.br",
  "ra3n.brenohomaraimoveis.com.br"
]
#method = "http01"
public = "/home/lagden/webapps/ra3n"
name = "BrenoCerts"
key_size = 4096


[[certificate]]
domains = [
  "itac.org.br",
  "www.itac.org.br",
  "uno.itac.org.br"
]
#method = "http01"
public = [
  "/home/lagden/webapps/tmpitac",
  "/home/lagden/webapps/tmpitac_uno"
]
name = "ItacCerts"
key_size = 4096
```

I just run:

```
{myuser@web531:~_0}$ letsencrypt_webfaction run
90 days until expiration of BrenoCerts. Skipping...
90 days until expiration of ItacCerts. Skipping...
```

But I ran the `acme-staging` before

**Comment by lagden** [comment]
I renamed the certificates and everything worked...
I think the certificate generated in staging is not being rewritten

```toml
[[certificate]]
#...
# name = "ItacCerts"
name = "ItacEduCerts"
```

```
{myuser@web531:~_0}$ letsencrypt_webfaction run
Issuing ItacEduCerts for the first time.
Your new certificate is now created and installed.
You will need to change your application to use the ItacEduCerts certificate.
Add the `--quiet` parameter in your cron task to remove this message.
```
